import Head from 'next/head'
import styles from '../styles/Home.module.css'

const posts = [
    {title: 'Test', excerpt: 'Test'},
    {title: 'Test2', excerpt: 'Test2'}
]
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.content}>
          <div className={styles.post_info}>
              {posts.map((post, index) => (
                  <div>
                      {post.title}
                      {post.excerpt}
                  </div>
              ))}
          </div>

          <div className={styles.post}>
            <div className={styles.post_1}>

            </div>
          </div>
      </div>

    </div>
  )
}
