import Head from 'next/head';
import {PostCard, PostWidget, Categories} from "../components";
import styles from '../styles/Home.module.scss'

const posts = [
    {title: 'Test', excerpt: 'Test'},
    {title: 'Test2', excerpt: 'Test2'}
]
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.content}>
          <div className={styles.post_info}>
              {posts.map((post) => (
                  <PostCard post={post} key={post.title}/>
              ))}
          </div>

          <div className={styles.post}>
            <div className={styles.post_1}>
                  <PostWidget/>
                <Categories/>
            </div>
          </div>
      </div>

    </div>
  )
}
