import Head from 'next/head';
import {PostCard, PostWidget, Categories} from "../components";
import styles from '../styles/Home.module.scss';
import { getPosts } from '../services';

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <div className={styles.content}>
          <div className={styles.post_info}>
              {posts.map((post) => (
                  <PostCard post={post.node} key={post.node.title}/>
              ))}
          </div>

          <div className={styles.post}>
            <div className={styles.post_1}>
                  <PostWidget/>
                <Categories/>
            </div>
          </div>
      </div>
    </div>
  )
}

export async function getStaticProps(params) {
  const posts = (await getPosts()) || [];
  
  return {
    props: {
      posts
    }
  }
}
